username = 'stockex-mainserver'
password = 'yLXLdxUHvfcxsosO'
connection_string = 'mongodb+srv://' + username + ':' + password + '@stockexcluster-beopo.gcp.mongodb.net/test?retryWrites=true&w=majority'
# connection_string = 'localhost:27017'
database_name = 'stockex'
